"""HTTP 请求、响应与入库流水线 Schema。"""

from app.interfaces.http.schemas.attachment import AttachmentUploadResponse
from app.interfaces.http.schemas.knowledge_base import (
    KnowledgeBaseOverview,
    PolicyDocumentOption,
    PolicyDocumentOptionList,
    RagMvpStatus,
)
from app.interfaces.http.schemas.policy_decision import (
    PolicyDecisionChecklistRequest,
    PolicyDecisionChecklistResponse,
    PolicyDecisionDataAcquisitionDebug,
    PolicyDecisionDataFieldTrace,
    PolicyDecisionDebugInfo,
    PolicyDecisionRequest,
    PolicyDecisionRequirementStatus,
    PolicyDecisionResponse,
)
from app.interfaces.http.schemas.policy_pipeline_common import (
    BlockSource,
    BlockType,
    DocumentFileType,
    ParseMethod,
    ParserStatus,
    PipelineStageName,
    PipelineStageResult,
    PipelineStatus,
)
from app.interfaces.http.schemas.policy_pipeline_content import (
    ChunkItem,
    ChunkSampleItem,
    ChunkSplitResult,
    PersistenceResult,
    SectionSplitItem,
    SectionSplitResult,
)
from app.interfaces.http.schemas.policy_pipeline_document import (
    AssembledLine,
    CleanedTextResult,
    FormatNormalizationResult,
    IntakeValidationResult,
    OcrProcessResult,
    ParsedBlock,
    ParsedDocumentResult,
    ParsedTextResult,
    ParseRoutingResult,
    PolicyPipelineRequest,
    RegisteredFileInfo,
)
from app.interfaces.http.schemas.policy_pipeline_response import PolicyPipelineResponse
from app.interfaces.http.schemas.policy_upload import (
    PolicyUploadIngestRequest,
    PolicyUploadPreviewResponse,
)
from app.interfaces.http.schemas.publication import (
    KnowledgePublicationRequest,
    KnowledgePublicationResponse,
)
from app.interfaces.http.schemas.retrieval import (
    AnswerCitation,
    RagAskRequest,
    RagAskResponse,
    RetrievalDebugInfo,
    RetrievalFilters,
    RetrievalHit,
    RetrievalSearchRequest,
    RetrievalSearchResponse,
    RetrievalStageDebug,
)
from app.interfaces.http.schemas.tender import (
    TenderArtifactResponse,
    TenderErrorResponse,
    TenderGenerateSkeletonResponse,
)

__all__ = [
    "AnswerCitation",
    "AttachmentUploadResponse",
    "AssembledLine",
    "BlockSource",
    "BlockType",
    "ChunkItem",
    "ChunkSampleItem",
    "ChunkSplitResult",
    "CleanedTextResult",
    "DocumentFileType",
    "FormatNormalizationResult",
    "IntakeValidationResult",
    "KnowledgeBaseOverview",
    "KnowledgePublicationRequest",
    "KnowledgePublicationResponse",
    "OcrProcessResult",
    "ParseMethod",
    "ParseRoutingResult",
    "ParsedBlock",
    "ParsedDocumentResult",
    "ParsedTextResult",
    "ParserStatus",
    "PersistenceResult",
    "PipelineStageName",
    "PipelineStageResult",
    "PipelineStatus",
    "PolicyDecisionChecklistRequest",
    "PolicyDecisionChecklistResponse",
    "PolicyDecisionDataAcquisitionDebug",
    "PolicyDecisionDataFieldTrace",
    "PolicyDecisionDebugInfo",
    "PolicyDecisionRequirementStatus",
    "PolicyDecisionRequest",
    "PolicyDecisionResponse",
    "PolicyDocumentOption",
    "PolicyDocumentOptionList",
    "PolicyPipelineRequest",
    "PolicyPipelineResponse",
    "PolicyUploadIngestRequest",
    "PolicyUploadPreviewResponse",
    "RagAskRequest",
    "RagAskResponse",
    "RagMvpStatus",
    "RegisteredFileInfo",
    "RetrievalDebugInfo",
    "RetrievalFilters",
    "RetrievalHit",
    "RetrievalSearchRequest",
    "RetrievalSearchResponse",
    "RetrievalStageDebug",
    "TenderArtifactResponse",
    "TenderErrorResponse",
    "TenderGenerateSkeletonResponse",
    "SectionSplitItem",
    "SectionSplitResult",
]
